---
# author: lework

- name: Check if zookeeper local file is already configured.
  stat: path={{ zookeeper_file_path }}
  connection: local
  register: zookeeper_file_result

- name: Create software files .
  file: path={{ software_files_path }} state=directory
  connection: local
  when: not zookeeper_file_result.stat.exists

- name: Download zookeeper file.
  get_url: url={{ zookeeper_file_url }} dest={{ software_files_path }}
  connection: local
  when: not zookeeper_file_result.stat.exists

- name: Copy zookeeper file to agent.
  unarchive:
    src: "{{ zookeeper_file_path }}"
    dest: "{{ software_install_path }}"
    creates: "{{ software_install_path}}/zookeeper-{{ zookeeper_version }}"

- name: Check if zookeeper remote soft link  is already configured.
  stat: path="{{ software_install_path }}/zookeeper"
  register: zookeeper_soft_link_result

- name: Create zookeeper dir soft link
  file: "src={{ software_install_path }}/zookeeper-{{ zookeeper_version }} dest={{ software_install_path }}/zookeeper state=link"
  when: not zookeeper_soft_link_result.stat.exists

- name: Config environment variable.
  lineinfile: dest=/etc/profile line='export PATH={{ software_install_path }}/zookeeper/bin/:$PATH'
