---
# author: lework

- name: backup | 创建存储备份的目录。
  file: path={{ deploy_code_history_path }}/{{ deploy_service }}-{{ ansible_date_time.date }}/ state=directory

- name: backup | 备份此次上线的代码。
  shell: "mv {{ deploy_code_online_path }}/* {{ deploy_code_history_path }}/{{ deploy_service }}-{{ ansible_date_time.date }}/"
